/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package wiew;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Lino
 */
public class Central extends javax.swing.JFrame {
    
     DefaultTableModel modelo= new DefaultTableModel();
    
    public Central() {
        initComponents();
        setLocationRelativeTo(null);
        modelo.addColumn("Clientes");
        modelo.addColumn("Tipo de cliente");
        modelo.addColumn("Servicios / Linea");
        modelo.addColumn("Costo de Teleseleccion");
        modelo.addColumn("Monto total a pagar");
        Tabla.setModel(modelo);
    }
       
    
   
    
    

    
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rastreo = new javax.swing.JButton();
        matutino = new javax.swing.JButton();
        addPerson = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        addLlamada = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        setFocusableWindowState(false);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));

        rastreo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rastreo.setForeground(new java.awt.Color(255, 255, 255));
        rastreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RS .png"))); // NOI18N
        rastreo.setContentAreaFilled(false);
        rastreo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rastreo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RS .png"))); // NOI18N
        rastreo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/RB.png"))); // NOI18N
        rastreo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        rastreo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rastreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rastreoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rastreoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rastreoMouseExited(evt);
            }
        });
        rastreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rastreoActionPerformed(evt);
            }
        });

        matutino.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        matutino.setForeground(new java.awt.Color(255, 255, 255));
        matutino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MS.png"))); // NOI18N
        matutino.setContentAreaFilled(false);
        matutino.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        matutino.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MS.png"))); // NOI18N
        matutino.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/MB.png"))); // NOI18N
        matutino.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        matutino.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        matutino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                matutinoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                matutinoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                matutinoMouseExited(evt);
            }
        });
        matutino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matutinoActionPerformed(evt);
            }
        });

        addPerson.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addPerson.setForeground(new java.awt.Color(255, 255, 255));
        addPerson.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AS.png"))); // NOI18N
        addPerson.setContentAreaFilled(false);
        addPerson.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addPerson.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AS.png"))); // NOI18N
        addPerson.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AB.png"))); // NOI18N
        addPerson.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        addPerson.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addPerson.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addPersonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addPersonMouseExited(evt);
            }
        });
        addPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPersonActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/EtecsaIcon.png"))); // NOI18N

        addLlamada.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addLlamada.setForeground(new java.awt.Color(255, 255, 255));
        addLlamada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LS.png"))); // NOI18N
        addLlamada.setContentAreaFilled(false);
        addLlamada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addLlamada.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LS.png"))); // NOI18N
        addLlamada.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LB.png"))); // NOI18N
        addLlamada.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        addLlamada.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addLlamada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addLlamadaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addLlamadaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addLlamadaMouseExited(evt);
            }
        });
        addLlamada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLlamadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(addLlamada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rastreo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(addPerson, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(matutino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(matutino, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rastreo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addLlamada, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cliente(s) con mayor uso de Servicios:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(688, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "", "    ", "", "", ""
            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Tabla);
        if (Tabla.getColumnModel().getColumnCount() > 0) {
            Tabla.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPersonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPersonMouseEntered
        addPerson.setText("Agregar cliente");
    }//GEN-LAST:event_addPersonMouseEntered

    private void addPersonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPersonMouseExited
        addPerson.setText("");
    }//GEN-LAST:event_addPersonMouseExited

    private void addPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPersonActionPerformed
    Clientes cliente=new Clientes(this, true);
      cliente.setVisible(true);
    }//GEN-LAST:event_addPersonActionPerformed

    private void rastreoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rastreoMouseEntered
        rastreo.setText("Rastreo de llamadas");
    }//GEN-LAST:event_rastreoMouseEntered

    private void rastreoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rastreoMouseExited
       rastreo.setText("");
    }//GEN-LAST:event_rastreoMouseExited

    private void rastreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rastreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rastreoActionPerformed

    private void matutinoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matutinoMouseEntered
         matutino.setText("Tabla horaria");
    }//GEN-LAST:event_matutinoMouseEntered

    private void matutinoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matutinoMouseExited
        matutino.setText("");
    }//GEN-LAST:event_matutinoMouseExited

    private void matutinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matutinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matutinoActionPerformed
   
    private void rastreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rastreoMouseClicked
     RastreoLlamadas rastreoLlamada=new RastreoLlamadas(this, true);
      rastreoLlamada.setVisible(true);
    }//GEN-LAST:event_rastreoMouseClicked

    private void matutinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matutinoMouseClicked
     TablaHoraria tabla = new TablaHoraria (this, true);
     tabla.setVisible(true);
    }//GEN-LAST:event_matutinoMouseClicked

    private void addLlamadaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addLlamadaMouseEntered
           addLlamada.setText("Agregar Llamada");
    }//GEN-LAST:event_addLlamadaMouseEntered

    private void addLlamadaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addLlamadaMouseExited
           addLlamada.setText("");
    }//GEN-LAST:event_addLlamadaMouseExited

    private void addLlamadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLlamadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addLlamadaActionPerformed

    private void addLlamadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addLlamadaMouseClicked
        Llamadas llamada=new Llamadas (this, true);
        llamada.setVisible(true);
    }//GEN-LAST:event_addLlamadaMouseClicked

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        
    }//GEN-LAST:event_TablaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Central.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Central.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Central.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Central.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Central().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton addLlamada;
    private javax.swing.JButton addPerson;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton matutino;
    private javax.swing.JButton rastreo;
    // End of variables declaration//GEN-END:variables
}
