/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

/**
 *
 * @author Lino
 */
public class SelectorTipoLlamada extends javax.swing.JFrame {

    /**
     * Creates new form SelectorTipoLlamada
     */
    public SelectorTipoLlamada() {
        initComponents();
        siguiente.setEnabled(false);
        setLocationRelativeTo(null);
    }
    
    
   private void AgregarBotones(){
       botones.add(opLocal);
       botones.add(opInterprovincial);
       botones.add(opInternacional);
   }
   
   private void habilitacionSiguiente(){
       
       if(opLocal.isSelected()==true || opInterprovincial.isSelected()==true  || opInternacional.isSelected()==true ){
           siguiente.setEnabled(true);
       }
   }
   
     private void llamarFormularios(){
         
           if(opInterprovincial.isSelected()==true){
              LlamadaNacionalInterprovincial nacional= new   LlamadaNacionalInterprovincial ();
              nacional.setVisible(true);
           
     }
           if(opInternacional.isSelected()==true){
               LlamadaInternacional  internacional = new  LlamadaInternacional ();
              internacional.setVisible(true);
              
     }
              if(opLocal.isSelected()==true){
              LlamadaNacionalLocal nacional= new   LlamadaNacionalLocal ();
              nacional.setVisible(true);
     }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        opLocal = new javax.swing.JRadioButton();
        opInterprovincial = new javax.swing.JRadioButton();
        opInternacional = new javax.swing.JRadioButton();
        siguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("¿Qué tipo de llamada desea agregar?");

        opLocal.setForeground(new java.awt.Color(255, 255, 255));
        opLocal.setText("Nacional Local");
        opLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opLocalActionPerformed(evt);
            }
        });

        opInterprovincial.setForeground(new java.awt.Color(255, 255, 255));
        opInterprovincial.setText("Nacional Interprovincial");
        opInterprovincial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opInterprovincialActionPerformed(evt);
            }
        });

        opInternacional.setForeground(new java.awt.Color(255, 255, 255));
        opInternacional.setText("Internacional");
        opInternacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opInternacionalActionPerformed(evt);
            }
        });

        siguiente.setText("Siguiente");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opInterprovincial)
                            .addComponent(opInternacional)
                            .addComponent(opLocal)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(siguiente)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 46, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(opLocal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opInterprovincial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opInternacional)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(siguiente)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
     llamarFormularios();
     setVisible(false);
    }//GEN-LAST:event_siguienteActionPerformed

    private void opLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opLocalActionPerformed
       AgregarBotones();
       habilitacionSiguiente();
    }//GEN-LAST:event_opLocalActionPerformed

    private void opInterprovincialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opInterprovincialActionPerformed
       AgregarBotones();
       habilitacionSiguiente();
    }//GEN-LAST:event_opInterprovincialActionPerformed

    private void opInternacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opInternacionalActionPerformed
       AgregarBotones();
       habilitacionSiguiente();
    }//GEN-LAST:event_opInternacionalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectorTipoLlamada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectorTipoLlamada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectorTipoLlamada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectorTipoLlamada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectorTipoLlamada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup botones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton opInternacional;
    private javax.swing.JRadioButton opInterprovincial;
    private javax.swing.JRadioButton opLocal;
    private javax.swing.JButton siguiente;
    // End of variables declaration//GEN-END:variables
}
